# The migration files contain two sections: 
# - up: The commands to execute on migration 
# - down: The commands to execute on rollback (optional) 
# check https://docs.rs/aragog_cli for complete documentation and examples 
---
up:
  - create_collection:
      name: Note
      wait_for_sync: false
  - create_index:
      name: Note_uri
      fields: ["uri"]
      collection: Note
      settings:
        type: persistent
        unique: false
        sparse: false
        deduplicate: false
down:
  - delete_index:
      name: Note_uri
      collection: Note
  - delete_collection:
      name: Note
