# The migration files contain two sections: 
# - up: The commands to execute on migration 
# - down: The commands to execute on rollback (optional) 
# check https://docs.rs/aragog_cli for complete documentation and examples 
---
up:
  - delete_index:
      name: Account_uri
      collection: Account
  - create_index:
      name: Account_remote_uri
      fields: ["remote.uri"]
      collection: Account
      settings:
        type: persistent
        unique: false
        sparse: false
        deduplicate: false
  - delete_index:
      name: Note_uri
      collection: Note
  - create_index:
      name: Note_remote_uri
      fields: ["remote.uri"]
      collection: Note
      settings:
        type: persistent
        unique: false
        sparse: false
        deduplicate: false
down:
  - delete_index:
      name: Account_remote_uri
      collection: Account
  - create_index:
      name: Account_uri
      fields: ["uri"]
      collection: Account
      settings:
        type: persistent
        unique: false
        sparse: false
        deduplicate: false
  - delete_index:
      name: Note_remote_uri
      collection: Note
  - create_index:
      name: Note_uri
      fields: ["uri"]
      collection: Note
      settings:
        type: persistent
        unique: false
        sparse: false
        deduplicate: false
